const GET_MOVIES_START = 'GET_MOVIES_START';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export { GET_MOVIES_START, GET_MOVIES_SUCCESS, GET_MOVIES_ERROR };
