const prefix = 'app/MoviesPage';

const GET_MOVIES_START = `${prefix}/GET_MOVIES_START`;
const GET_MOVIES_SUCCESS = `${prefix}/GET_MOVIES_SUCCESS`;
const GET_MOVIES_ERROR = `${prefix}/GET_MOVIES_ERROR`;
const SET_CURRENT_PAGE_PARAM = `${prefix}/SET_CURRENT_PAGE_PARAM`;
const SET_SORT_PARAM = `${prefix}/SET_SORT_PARAM`;
const SET_LANGUAGE_PARAM = `${prefix}/SET_LANGUAGE_PARAM`;

export {
  GET_MOVIES_START,
  GET_MOVIES_SUCCESS,
  GET_MOVIES_ERROR,
  SET_CURRENT_PAGE_PARAM,
  SET_SORT_PARAM,
  SET_LANGUAGE_PARAM,
};
